apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: applications.applicationconnector.kyma-project.io
spec:
  group: applicationconnector.kyma-project.io
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              properties:
                compassMetadata:
                  type: object
                  required:
                  - "authentication"
                  properties:
                    applicationId:
                      type: string
                    authentication:
                      type: object
                      required:
                      - "clientIds"
                      properties:
                        clientIds:
                          type: array
                          items:
                            type: string
                accessLabel:
                  type: string
                  maxLength: 63
                  pattern: '^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$'
                description:
                  type: string
                skipInstallation:
                  type: boolean
                skipVerify:
                  type: boolean
                encodeUrl:
                  type: boolean
                  default: true
                labels:
                  nullable: true
                  additionalProperties:
                    type: string
                  type: object
                tenant:
                  type: string
                group:
                  type: string
                tags:
                  nullable: true
                  description: New fields used by V2 version
                  items:
                    type: string
                  type: array
                displayName:
                  type: string
                providerDisplayName:
                  type: string
                longDescription:
                  type: string
                services:
                  type: array
                  items:
                    type: object
                    required:
                    - "id"
                    - "name"
                    - "displayName"
                    - "providerDisplayName"
                    - "description"
                    - "entries"
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      identifier:
                        type: string
                      labels:
                        nullable: true
                        additionalProperties:
                          type: string
                        description: Deprecated
                        type: object
                      displayName:
                        type: string
                      description:
                        type: string
                      longDescription:
                        type: string
                      providerDisplayName:
                        type: string
                      authCreateParameterSchema:
                        description: New fields used by V2 version
                        type: string
                      entries:
                        type: array
                        items:
                          type: object
                          required:
                          - "type"
                          properties:
                            apiType:
                              type: string
                            type:
                              type: string
                              enum:
                              - "API"
                              - "Events"
                            gatewayUrl:
                              type: string
                            centralGatewayUrl:
                              type: string
                            accessLabel:
                              type: string
                              maxLength: 63
                              pattern: '^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$'
                            targetUrl:
                              type: string
                            id:
                              type: string
                            name:
                              description: New fields used by V2 version
                              type: string
                            requestParametersSecretName:
                              type: string
                            specificationUrl:
                              type: string
                            credentials:
                              type: object
                              required:
                              - "type"
                              - "secretName"
                              properties:
                                type:
                                  type: string
                                secretName:
                                  type: string
                                authenticationUrl:
                                  type: string
                                csrfInfo:
                                  type: object
                                  required:
                                  - "tokenEndpointURL"
                                  properties:
                                    tokenEndpointURL:
                                      type: string
                      tags:
                        type: array
                        items:
                          type: string
              type: object
            status:
              properties:
                installationStatus:
                  description: Represents the status of Application release installation
                  properties:
                    description:
                      type: string
                    status:
                      type: string
                  required:
                  - status
                  type: object
              required:
              - installationStatus
              type: object
  scope: Cluster
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
    - app
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: compassconnections.compass.kyma-project.io
spec:
  group: compass.kyma-project.io
  names:
    kind: CompassConnection
    listKind: CompassConnectionList
    plural: compassconnections
    singular: compassconnection
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                managementInfo:
                  properties:
                    connectorUrl:
                      description: 'URL used for maintaining the secure connection.'
                      type: string
                    directorUrl:
                      description: 'URL used for fetching Applications.'
                      type: string
                  required:
                    - connectorUrl
                    - directorUrl
                  type: object
                refreshCredentialsNow:
                  description: 'If set to `true`, ignores certificate expiration date and refreshes in the next round.'
                  type: boolean
                resyncNow:
                  description: 'If set to `true`, ignores `APP_MINIMAL_COMPASS_SYNC_TIME` and syncs in the next round.'
                  type: boolean
              required:
                - managementInfo
              type: object
            status:
              properties:
                connectionState:
                  type: string
                connectionStatus:
                  description: 'Represents the status of the connection to
                    Compass.'
                  properties:
                    certificateStatus:
                      description: 'Specifies the certificate issue and expiration dates.'
                      properties:
                        acquired:
                          description: 'Specifies when the certificate was acquired.'
                          format: date-time
                          nullable: true
                          type: string
                        notAfter:
                          description: 'Specifies when the certificate stops being valid.'
                          format: date-time
                          nullable: true
                          type: string
                        notBefore:
                          description: 'Specifies when the certificate becomes valid.'
                          format: date-time
                          nullable: true
                          type: string
                      type: object
                    error:
                      type: string
                    established:
                      description: 'Specifies when the connection was established.'
                      format: date-time
                      nullable: true
                      type: string
                    lastSuccess:
                      description: 'Specifies the date of the last successful synchronization with the Connector.'
                      format: date-time
                      nullable: true
                      type: string
                    lastSync:
                      description: 'Specifies the date of the last synchronization attempt.'
                      format: date-time
                      nullable: true
                      type: string
                    renewed:
                      description: 'Specifies the date of the last certificate renewal.'
                      format: date-time
                      nullable: true
                      type: string
                  required:
                    - certificateStatus
                  type: object
                synchronizationStatus:
                  description: 'Provides the status of the synchronization with the Director.'
                  nullable: true
                  properties:
                    error:
                      type: string
                    lastAttempt:
                      description: 'Specifies the date of the last synchronization attempt with the Director.'
                      format: date-time
                      nullable: true
                      type: string
                    lastSuccessfulApplication:
                      description: 'Specifies the date of the last successful application of resources fetched from Compass.'
                      format: date-time
                      nullable: true
                      type: string
                    lastSuccessfulFetch:
                      description: 'Specifies the date of the last successful fetch of resources from the Director.'
                      format: date-time
                      nullable: true
                      type: string
                  type: object
              required:
                - connectionState
                - connectionStatus
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
