name: Build ACM

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-module:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'

    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: create-module
      run: make -C hack/ci module-build
      env:
        IMG: "europe-docker.pkg.dev/kyma-project/dev/application-connector-manager:PR-${{ github.event.number }}"
        KUSTOMIZE_VERSION: "v4.5.6"
        MODULE_REGISTRY: "https://ghcr.io/${GITHUB_REPOSITORY}/unsigned"
        MODULE_SHA: "PR-${{ github.event.number }}"
    - name: Adding markdown
      run: echo -e "### application-connector-manager.yaml\n\`\`\`\n$(cat moduletemplate.yaml)\n\`\`\`" >> $GITHUB_STEP_SUMMARY
