name: run-cra-k3d
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  run-cra-k3d:
    uses: "./.github/workflows/reusable-k3d-agent-test.yml"
    secrets:
      host: ${{ secrets.COMPASS_HOST }}
      id: ${{ secrets.COMPASS_CLIENT_ID }}
      secret: ${{ secrets.COMPASS_CLIENT_SECRET }}
