name: k3d CRA test
on:
  workflow_call:
    inputs:
       k3d-version:
         required: true
         type: string
         default: v5.6.0
    secrets:
      compass-host:
        required: true
      compass-client-id:
        required: true
      compass-client-secret:
        required: true
jobs:
  test-cra:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2
      - uses: azure/setup-helm@v4.1.0
        id: install-helm
      - name: checkout
        uses: actions/checkout@v3
      - name: install-k3d
        env:
          K3D_URL: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
          DEFAULT_K3D_VERSION: ${{ inputs.k3d-version }}
        run: curl --silent --fail $K3D_URL | TAG=$DEFAULT_K3D_VERSION bash
      - name: setup-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            /home/runner/work/application-connector-manager/application-connector-manager/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: run-tests
        env:
          COMPASS_CLIENT_ID: ${{ secrets.compass-client-id }}
          COMPASS_CLIENT_SECRET: ${{ secrets.compass-client-secret }}
          COMPASS_HOST: ${{ secrets.compass-host }} 
        run: make -C tests/hack/ci k3d-agent-tests
      - name: archive-logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compass-runtime-agent-test-results
          path: compass-runtime-agent-test.log
