name: Run vuln check
on:
  push:
    branches: [ "main", "govulncheck-test" ]
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: vulncheck
      uses: golang/govulncheck-action@v1
